/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import entity.Course;
import entity.Skema;
import java.io.File;
import java.util.ArrayList;
import selenium.Selenium;

/**
 *
 * @author Lenovo
 */
public class RecordGui extends javax.swing.JFrame {
    SoundRecorder soundrec = new SoundRecorder();
    File wav;
    Selenium s = new Selenium();
    Skema skema = new Skema();

    /**
     * Creates new form RecordGui
     */
    public RecordGui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        UserTextField = new javax.swing.JTextPane();
        CreateUserButton = new javax.swing.JButton();
        RecordButton = new javax.swing.JButton();
        RecordButtonTwo = new javax.swing.JButton();
        RecordButtonThree = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        RecordOneStatus = new javax.swing.JLabel();
        RecordTwoStatus = new javax.swing.JLabel();
        RecordThreeStatus = new javax.swing.JLabel();
        SkemaGetterButton = new javax.swing.JButton();
        SkemaTextField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        SkemaFieldOne = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        SkemaFieldTwo = new javax.swing.JTextArea();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(UserTextField);

        CreateUserButton.setText("Create User");
        CreateUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateUserButtonActionPerformed(evt);
            }
        });

        RecordButton.setText("Record 1");
        RecordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecordButtonActionPerformed(evt);
            }
        });

        RecordButtonTwo.setText("Record 2");
        RecordButtonTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecordButtonTwoActionPerformed(evt);
            }
        });

        RecordButtonThree.setText("Record 3");
        RecordButtonThree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecordButtonThreeActionPerformed(evt);
            }
        });

        RecordOneStatus.setText("Not Done");

        RecordTwoStatus.setText("Not Done");

        RecordThreeStatus.setText("Not Done");

        SkemaGetterButton.setText("Fetch Skema");
        SkemaGetterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SkemaGetterButtonActionPerformed(evt);
            }
        });

        SkemaFieldOne.setColumns(20);
        SkemaFieldOne.setRows(5);
        jScrollPane2.setViewportView(SkemaFieldOne);

        SkemaFieldTwo.setColumns(20);
        SkemaFieldTwo.setRows(5);
        jScrollPane3.setViewportView(SkemaFieldTwo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(RecordButtonThree, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(RecordButtonTwo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(RecordButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CreateUserButton)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(RecordOneStatus)
                                    .addComponent(RecordTwoStatus)
                                    .addComponent(RecordThreeStatus)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(SkemaTextField)
                                .addGap(18, 18, 18)
                                .addComponent(SkemaGetterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CreateUserButton)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RecordButton)
                            .addComponent(RecordOneStatus)))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RecordButtonTwo)
                    .addComponent(RecordTwoStatus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RecordButtonThree)
                    .addComponent(RecordThreeStatus))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SkemaGetterButton)
                    .addComponent(SkemaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CreateUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateUserButtonActionPerformed
User user = new User();
user.createUser(UserTextField.getText());// TODO add your handling code here:
    }//GEN-LAST:event_CreateUserButtonActionPerformed

    private void RecordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecordButtonActionPerformed
         
        soundrec.startRecording(UserTextField.getText()+"\\record.wav");
        RecordOneStatus.setText("Done");
    }//GEN-LAST:event_RecordButtonActionPerformed

    private void RecordButtonTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecordButtonTwoActionPerformed
       soundrec.startRecording(UserTextField.getText()+"\\record2.wav");
        RecordTwoStatus.setText("Done");
    }//GEN-LAST:event_RecordButtonTwoActionPerformed

    private void RecordButtonThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecordButtonThreeActionPerformed
        soundrec.startRecording(UserTextField.getText()+"\\record3.wav");
        RecordThreeStatus.setText("Done");        // TODO add your handling code here:
    }//GEN-LAST:event_RecordButtonThreeActionPerformed

    private void SkemaGetterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SkemaGetterButtonActionPerformed
skema = s.callSelenium(SkemaTextField.getText());
ArrayList<Course> skemaList = skema.getCourses();
SkemaFieldOne.setText(skemaList.get(0).toString());
SkemaFieldTwo.setText(skemaList.get(1).toString());
    }//GEN-LAST:event_SkemaGetterButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecordGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecordGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecordGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecordGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecordGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreateUserButton;
    private javax.swing.JButton RecordButton;
    private javax.swing.JButton RecordButtonThree;
    private javax.swing.JButton RecordButtonTwo;
    private javax.swing.JLabel RecordOneStatus;
    private javax.swing.JLabel RecordThreeStatus;
    private javax.swing.JLabel RecordTwoStatus;
    private javax.swing.JTextArea SkemaFieldOne;
    private javax.swing.JTextArea SkemaFieldTwo;
    private javax.swing.JButton SkemaGetterButton;
    private javax.swing.JTextField SkemaTextField;
    private javax.swing.JTextPane UserTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
